version: '3.7'

services:
  ms-sql-server:
    #container_name: ms-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    deploy:
    #  mode: replicated
      replicas: 1
    # restart: always
      restart_policy:
        condition: on-failure
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1q2w3E*#"
    networks:
      - network_app
    volumes:
      - my-volume:/var/opt/mssql
  netcoreapp:
    #container_name: netcoreapp
    #build:
    #  dockerfile: ./WebsiteTinTuc.Admin.Web.Host/Dockerfile
    #  context: .
    image: netcoreapp:latest
    deploy:
      mode: replicated
      replicas: 5
    # restart: always
      restart_policy:
        condition: on-failure
    ports:
      - "5000:21021"
    depends_on:
      - ms-sql-server
    networks:
      - network_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=ms-sql-server; Database=TuyenDungDB; User Id=sa;Password=1q2w3E*#;
      - App__ServerRootAddress=http://netcoreapp:21021
      - Kestrel__Endpoints__Http__Url=http://netcoreapp:21021
    volumes:
      - netcore-volume:/app/wwwroot
networks:
  network_app:
    # driver: bridge
    driver: overlay
    name: net1

volumes:
  my-volume: {}
  netcore-volume: {}